const Users = [
  {
    profilePicture: "person/1.jpg",
    username: "Tyrell Atkinson",
    email: "tyrell@test.com",
    coverPicture: "post/1.jpg",
  },
  {
    id: 2,
    profilePicture: "person/2.jpg",
    username: "Adriana Reeves",
    email: "adriana@test.com",
    coverPicture: "post/2.jpg",
  },
  {
    id: 3,
    profilePicture: "person/3.jpg",
    username: "Ross O'Gallagher",
    email: "ross@test.com",
    coverPicture: "post/3.jpg",
  },
  {
    id: 4,
    profilePicture: "person/4.jpg",
    username: "Farhan Ali",
    email: "farhan@test.com",
    coverPicture: "post/4.jpg",
  },
  {
    id: 5,
    profilePicture: "person/5.jpg",
    username: "Chester Howard",
    email: "chester@test.com",
    coverPicture: "post/5.jpg",
  },
  {
    id: 6,
    profilePicture: "person/6.jpg",
    username: "Ana Barr",
    email: "ana@test.com",
    coverPicture: "post/6.jpg",
  },
  {
    id: 7,
    profilePicture: "person/7.jpg",
    username: "Lucian Barrett",
    email: "lucian@test.com",
    coverPicture: "post/7.jpg",
  },
  {
    id: 8,
    profilePicture: "person/8.jpg",
    username: "Alissa Bray",
    email: "alissa@test.com",
    coverPicture: "post/8.jpg",
  },
  {
    id: 9,
    profilePicture: "person/9.jpg",
    username: "Wilma Donnelly",
    email: "wilma@test.com",
    coverPicture: "post/9.jpg",
  },
  {
    id: 10,
    profilePicture: "person/10.jpg",
    username: "Anish Clarke",
    email: "anish@test.com",
    coverPicture: "post/10.jpg",
  },
];

const Posts = [
  {
    id: 1,
    desc: "Every moment is a fresh beginning.",
    photo: "post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Love For All, Hatred For None.",
    photo: "post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];

module.exports = {Users, Posts}