GET http://localhost:3001

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json
 
 {
    "username":"Rishabh",
    "email": "test@test.com",
    "password": "password"
 }

###
 POST http://localhost:3001/api/auth/login
Content-Type: application/json
 
 {
    "email": "test@test.com", 
    "password": "password"
 }