###
GET http://localhost:3001/api/posts

###
POST http://localhost:3001/api/posts
Content-Type: application/json
 
{
   "userId" : "6428eee42f93eb4cbaecd578",
   "desc": "first post by rishabh"    
}

###
GET http://localhost:3001/api/posts/timeline/all
Content-Type: application/json
 
{
   "userId" : "6428ee9b2f93eb4cbaecd571"     
}

###
GET http://localhost:3001/api/posts/profile/Rishabh
