###
GET http://localhost:3001/api/posts

###
POST http://localhost:3001/api/posts
Content-Type: application/json
 
{
   "userId" : "6428eee42f93eb4cbaecd578",
   "desc": "first post by rishabh"    
}

###
GET http://localhost:3001/api/posts/timeline/all
Content-Type: application/json
 
{
   "userId" : "6428ee9b2f93eb4cbaecd571"     
}

###
GET http://localhost:3001/api/posts/profile/Rishabh

###
PUT http://localhost:3001/api/posts/642a57ee91b3f101c669bc7b/like
Content-Type: application/json

{
   "userId" : "6428ee9b2f93eb4cbaecd571"     
}

###
POST http://localhost:3001/api/posts/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

{{READFILE "test.png"}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:3001/api/testing/reset
